#!/bin/bash


echo "looking for old version of remote-db-download"

if [ -f "/etc/remote-db-download.conf" ]; then 
        sudo rm -f /etc/remote-db-download.conf
        echo "Removed old config from /etc/..."
fi


if [ -f "$HOME/bin/remote-db-download" ]; then 
	sudo rm -f $HOME/bin/remote-db-download
	echo "Removed old remote-db-download from ~/bin..."
fi

if [ -f "/usr/local/bin/remote-db-download" ]; then
        sudo rm -f /usr/local/bin/remote-db-download
        echo "Removed old remote-db-download from ~/usr/local/bin..."
fi


if [ -f "/usr/bin/remote-db-download" ]; then
        sudo rm -f /usr/bin/remote-db-download
        echo "Removed old remote-db-download from ~/usr/bin..."
fi


if [ -f "/usr/share/applications/remote-db-download.desktop" ]; then
        sudo rm -f /usr/share/applications/remote-db-download.desktop
        echo "Removed old remote-db-download from ~/usr/share/app..."
fi

if [ -f "/usr/share/icons/remote-db-download.xpm" ]; then
        sudo rm -f /usr/share/icons/remote-db-download.xpm
        echo "Removed old remote-db-download from ~/usr/share/icons/app..."
fi


if [ -f "/usr/share/doc/remote-db-download/changelog.Debian.gz" ]; then
        sudo rm -f /usr/share/doc/remote-db-download/changelog.Debian.gz
        echo "Removed old remote-db-download docs from ~/usr/share/doc/..."
fi

if [ -f "/usr/share/doc/remote-db-download/copyright" ]; then
        sudo rm -f /usr/share/doc/remote-db-download/copyright
        echo "Removed old remote-db-download docs from ~/usr/share/doc/..."
fi

if [ -f "/usr/share/man/man1/remote-db-download.1.gz" ]; then
        sudo rm -f /usr/share/man/man1/remote-db-download.1.gz
        echo "Removed old remote-db-download user man from ~/usr/share/man/man1/..."
fi